apiVersion: v1
kind: Pod
metadata:
  name: robo-web
  labels:
    module: web-container
spec:
 containers:
   - name: rs-web
     image: krishnateja9/k8-webui:1.0
     imagePullPolicy: Always
     ports:
       - containerPort: 80
     resources:
       requests:
         cpu: "85m"
         memory: "120Mi"
       limits:
         cpu: "95m"
         memory: "135Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
      module: web-container
  ports:
     - protocol: TCP
       port: 80
       targetPort: 80