apiVersion: v1 
kind: ConfigMap 
metadata:
  name: catalogue-config
data:
 MONGO_URL: 'mongodb://mongodb-service:80/catalogue'
 
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
   module: catalogue
spec:
 containers:
   - name: catalogue
     image: krishnateja9/k8-catalogue:1.0
     envFrom:
       - configMapRef:
           name: catalogue-config       
     resources:
        requests:
          cpu: "75m"
          memory: "120Mi"
        limits:
          cpu: "90m"
          memory: "140Mi"
     
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    module: catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
