apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    module: mongodb
    tier: db
spec:
  containers:
    - name: mongodb
      image: krishnateja9/k8-mongodb:1.1
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "80m"
          memory: "120Mi"
        limits:
          cpu: "90m"
          memory: "145Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
     module: mongodb
     tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017