apiVersion: v1 
kind: Pod 
metadata: 
  name: redis 
  labels: 
    module: redis 
    tier: db 
spec: 
  containers:
    - name: redis 
      image: redis 
      resources: 
        requests: 
          cpu: "120m"
          memory: "89Mi"
        limits:
          cpu: "135m" 
          memory: "95Mi"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: redis-service 
spec: 
  selector: 
       module: redis 
       tier: db
  ports:
   - protocol: TCP 
     port: 6379
     targetPort: 6379
               